#!/usr/bin/env bash
# vim: ft=sh
PACKAGES="${PACKAGES} vim-enhanced gvim php php-dbg"
PACKAGES="${PACKAGES} php-json php-mbstring php-pdo php-pgsql php-xml"
PACKAGES="${PACKAGES} xclip vagrant VirtualBox-5.1 openssl-devel"
PACKAGES="${PACKAGES} readline-devel sqlite-devel"

# First things first
sudo dnf install -y kernel-devel

# Install virtualbox repository
curl -O http://download.virtualbox.org/virtualbox/rpm/fedora/virtualbox.repo
sudo mv virtualbox.repo /etc/yum.repos.d/

# Update DNF metadata
sudo dnf update -y

# Install the packages
for PACKAGE in "$PACKAGES"; do
  sudo dnf install -y $PACKAGE
done

# Add the current user into virtual box users
sudo usermod -a -G vboxusers $USER

# Upgrade pip
sudo pip install --upgrade pip

# Remove the current composer install
if [ -f /usr/local/bin/composer ]; then
  sudo rm -f /usr/local/bin/composer
fi

# Download the composer setup
curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer
sudo chmod +x /usr/local/bin/composer

# Setup composer
if [ -f composer-setup.php ]; then
  sudo php composer-setup.php --install-dir=/usr/local/bin --filename=composer
  rm -f composer-setup.php
else
  exit 1
fi

# Turn composer into a executable
sudo chmod +x /usr/local/bin/composer

