#!/usr/bin/env bash
# vim: ft=sh
IFS=$'\n\t'

DOTFILES_DIR=~/dotfiles
STOW_FILES=("bash" "git" "npm" "ssh" "tmux" "vim")

# Install Homebrew
if [ ! -f /usr/local/bin/brew ]; then
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

  brew tap homebrew/bundle
fi

# Clone the repository into the dotfiles dir
if [ ! -d $DOTFILES_DIR ]; then
  git clone https://github.com/diegoholiveira/dotfiles.git $DOTFILES_DIR
fi

# Install all dependencies using the Brewfile
cd $DOTFILES_DIR
  echo 'Installing dependencies using brew...'

  brew bundle > /dev/null
cd - > /dev/null

# Add the new shell to the list of allowed shells
grep -q "/usr/local/bin/bash" /etc/shells
if [ $? -ne 0 ]; then
  sudo bash -c 'echo /usr/local/bin/bash >> /etc/shells'
fi

# change to the new shell
if [ "$SHELL" == "/bin/bash" ]; then
  chsh -s /usr/local/bin/bash
fi

# Configure iTerm2 to load my preferences from my dotfiles folder
defaults write com.googlecode.iterm2.plist PrefsCustomFolder -string "$DOTFILES_DIR"
defaults write com.googlecode.iterm2.plist LoadPrefsFromCustomFolder -bool true

# Link the profiles to my versions
rm -f ~/.npmrc
cd $DOTFILES_DIR
  for APP in ${STOW_FILES[@]}; do
    stow ${APP}
  done
cd - > /dev/null

. ~/.bashrc

# install pip packages
echo 'Installing python packages using pip...'
pip install \
  flake8 \
  pycodestyle \
  vim-vint \
  > /dev/null

# Generates a ssh key for my user
if [ ! -f ~/.ssh/id_rsa ]; then
  ssh-keygen -t rsa -b 4096 -C "contato@diegoholiveira.com" -N "" -f ~/.ssh/id_rsa -q

  echo "------------------------------------------------------------------------------"
  echo "Final instructions"
  echo "------------------------------------------------------------------------------"
  echo ""
  echo "To secure your ssh key, please add a passphrase to it using the command above:"
  echo "    ssh-keygen -p -f ~/.ssh/id_rsa"
  echo ""
  echo "Before start using the computer, please restart the SO to reload all changes"
  echo "made by this script!"
  echo ""
fi
