#!/usr/bin/env bash
# vim: ft=sh

# Environment variables
BREW_PKGS="ansible bash bash-completion git python pyenv pyenv-virtualenv"
BREW_PKGS="${BREW_PKGS} tree tmux stow vcprompt ssh-copy-id rust scala sbt"
BREW_PKGS="${BREW_PKGS} node php70 php70-ast phan composer thefuck httpie"
CASK_APPS="iterm2 firefox spotify java send-to-kindle unrarx flux"
CASK_APPS="${CASK_APPS} docker vagrant virtualbox sequel-pro sublime-text"

# Install Homebrew
if [ ! -f /usr/local/bin/brew ]; then
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
else
  brew update
fi

# Install Cask
if ! brew tap | grep -q "caskroom/cask"; then
  brew tap caskroom/cask
else
  brew cask update
fi

# Tap homebrew/php
if ! brew tap | grep -q "homebrew/php"; then
  brew tap homebrew/php
fi

# Install Cask apps
for APP in $CASK_APPS; do
  brew cask install $APP
done

# Install Brew packages
for PKG in $BREW_PKGS; do
  if brew list -1 | grep -q "^${PKG}\$"; then
    brew upgrade $PKG
  else
    brew install $PKG
  fi
done

# Replace the system vim for a better vim
if brew list -1 | grep -q "^macvim\$"; then
  brew unlinkapps macvim
  brew upgrade macvim --with-override-system-vim
else
  brew install macvim --with-override-system-vim
fi

# Link macvim to the apps
brew linkapps macvim

# Import iTerm2 configs
defaults import com.googlecode.iterm2 ${DOTFILES_DIR}/iterm2.plist

# Add the new shell to the list of allowed shells
grep -q "/usr/local/bin/bash" /etc/shells
if [ $? -ne 0 ]; then
  sudo bash -c 'echo /usr/local/bin/bash >> /etc/shells'
fi

# change to the new shell
if [ "$SHELL" == "/bin/bash" ]; then
  chsh -s /usr/local/bin/bash
fi

