#!/usr/bin/env bash

DOTFILES_DIR=~/dotfiles
STOW_FILES=("fzf" "git" "npm" "ripgrep" "ssh" "tmux" "vim" "zsh")

# Install Homebrew
if [ ! -f /usr/local/bin/brew ]; then
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

  brew tap homebrew/bundle
fi

# Clone the repository into the dotfiles dir
if [ ! -d $DOTFILES_DIR ]; then
  git clone https://github.com/diegoholiveira/dotfiles.git $DOTFILES_DIR
fi

# Configure nord-dircolors
if [ ! -f ~/.dir_colors ]; then
  curl -sSkLo ~/.dir_colors https://raw.githubusercontent.com/arcticicestudio/nord-dircolors/develop/src/dir_colors
fi

# Install all dependencies using the Brewfile
(
  if [ ! -d /usr/local/sbin ]; then
    sudo mkdir -p /usr/local/sbin || true
    sudo chown "$USER:admin" /usr/local/sbin || true
  fi

  cd $DOTFILES_DIR || exit 1
  echo 'Installing dependencies using brew...'

  brew bundle >/dev/null
)

# Add the new shell to the list of allowed shells
if ! grep -q "/usr/local/bin/zsh" /etc/shells; then
  sudo zsh -c 'echo /usr/local/bin/zsh >> /etc/shells'
fi

# change to the new shell
if [ "$SHELL" != "/usr/local/bin/zsh" ]; then
  chsh -s /usr/local/bin/zsh
fi

# Link the profiles to my versions
rm -f ~/.npmrc
(
  cd $DOTFILES_DIR || exit 1
  for APP in "${STOW_FILES[@]}"; do
    stow "${APP}"
  done
)

# Generates a ssh key for my user
if [ ! -f ~/.ssh/id_rsa ]; then
  ssh-keygen -t rsa -b 4096 -C "contato@diegoholiveira.com" -N "" -f ~/.ssh/id_rsa -q
fi

$DOTFILES_DIR/setup-npm
$DOTFILES_DIR/setup-python
$DOTFILES_DIR/setup-tmux
$DOTFILES_DIR/setup-vim
$DOTFILES_DIR/setup-macos

echo "------------------------------------------------------------------------------"
echo "Final instructions"
echo "------------------------------------------------------------------------------"
echo
echo "Before start using the computer, please restart the SO to reload all changes"
echo "made by this script!"
echo
