#!/usr/bin/env bash

DOTFILES_DIR=~/dotfiles
STOW_FILES=("bat" "fzf" "git" "gnupg" "npm" "ripgrep" "starship" "ssh" "tmux" "vim" "zsh")

# Install Homebrew
if [ ! -f /usr/local/bin/brew ]; then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

  brew tap homebrew/bundle
fi

# Clone the repository into the dotfiles dir
if [ ! -d $DOTFILES_DIR ]; then
  git clone https://github.com/diegoholiveira/dotfiles.git $DOTFILES_DIR
fi

# Configure nord-dircolors
if [ ! -f ~/.dir_colors ]; then
  curl -sSkLo ~/.dir_colors https://raw.githubusercontent.com/arcticicestudio/nord-dircolors/develop/src/dir_colors
fi

sudo chmod -R 755 /usr/local/*
sudo chown -R $(whoami):admin /usr/local/*

# Install all dependencies using the Brewfile
(
  if [ ! -d /usr/local/sbin ]; then
    sudo mkdir -p /usr/local/sbin || true
    sudo chown "$USER:admin" /usr/local/sbin || true
  fi

  cd $DOTFILES_DIR || exit 1
  echo 'Installing dependencies using brew...'

  brew bundle
)

# Add the new shell to the list of allowed shells
if ! grep -q "/usr/local/bin/zsh" /etc/shells; then
  sudo zsh -c 'echo /usr/local/bin/zsh >> /etc/shells'
fi

# change to the new shell
if [ "$SHELL" != "/usr/local/bin/zsh" ]; then
  chsh -s /usr/local/bin/zsh
fi

# Link the profiles to my versions
rm -f ~/.npmrc
(
  cd $DOTFILES_DIR || exit 1
  for APP in "${STOW_FILES[@]}"; do
    stow "${APP}"
  done
)

$DOTFILES_DIR/setup-macos

echo "------------------------------------------------------------------------------"
echo "Final instructions"
echo "------------------------------------------------------------------------------"
echo
echo "Before start using the computer, please restart the SO to reload all changes"
echo "made by this script!"
echo
echo "After configure the git client properly, please run the file:"
echo "    $ ~/dotfiles/setup-after-git"
