#!/usr/bin/env bash
# vim: ft=sh
PACKAGES="${PACKAGES} vim-enhanced gvim php php-ast php-dbg"
PACKAGES="${PACKAGES} php-json php-mbstring php-pdo php-pgsql php-xml"
PACKAGES="${PACKAGES} dejavu-sans-fonts dejavu-sans-mono-fonts xclip"

# First things first
sudo dnf install -y kernel-devel

# Install virtualbox
sudo dnf install -y http://download.virtualbox.org/virtualbox/5.1.4/VirtualBox-5.1-5.1.4_110228_fedora24-1.x86_64.rpm

# Add the current user into virtual box users
sudo usermod -a -G vboxusers $USER

# Install Remi's repository
sudo dnf install -y http://rpms.remirepo.net/fedora/remi-release-24.rpm

# Enable Remi's repository
sudo dnf config-manager --set-enabled remi-php70

# Update DNF metadata
sudo dnf update -y

# Install the packages
for PACKAGE in "$PACKAGES"; do
  sudo dnf install -y $PACKAGE
done

# Install Vagrant 1.8.5
sudo dnf install -y https://releases.hashicorp.com/vagrant/1.8.5/vagrant_1.8.5_x86_64.rpm

# Upgrade pip
sudo pip install --upgrade pip

# Install pyenv
if [ ! -d ~/.pyenv ]; then
  curl -sS https://raw.githubusercontent.com/yyuu/pyenv-installer/master/bin/pyenv-installer | bash
fi

# Remove the current composer install
if [ -f /usr/local/bin/composer ]; then
  sudo rm -f /usr/local/bin/composer
fi

# Download the composer setup
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('SHA384', 'composer-setup.php') === 'e115a8dc7871f15d853148a7fbac7da27d6c0030b848d9b3dc09e2a0388afed865e6a3d6b3c0fad45c48e2b5fc1196ae') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"

# Setup composer
if [ -f composer-setup.php ]; then
  sudo php composer-setup.php --install-dir=/usr/local/bin --filename=composer
  rm -f composer-setup.php
else
  exit 1
fi

# Turn composer into a executable
sudo chmod +x /usr/local/bin/composer

