add_newline = true
format = "$directory$git_branch$git_status$python\n$character"
[character]
success_symbol = "[%](bold green)"
error_symbol = "[%](bold red)"
[directory]
truncation_length = 12
truncate_to_repo = false
truncation_symbol = "…/"
style = "bold blue"
[git_branch]
format = "on [$branch]($style) "
style = ""
[git_status]
style = "bold yellow"
ahead = ">"
behind = "<"
diverged = "<>"
renamed = "r"
deleted = "x"
