" vim: foldmethod=marker:foldlevel=0
scriptencoding utf-8
" Fonts {{{
set antialias
set guifont=Menlo:h14
" }}}
" Interface layout {{{
" Hide toolbar
set guioptions-=T
" Hide right scroll bar
set guioptions-=r
set guioptions-=R
" Hide left scroll bar
set guioptions-=l
set guioptions-=L
" }}}
