" vim: foldmethod=marker:foldlevel=0
scriptencoding utf-8
if &term =~# '^screen'
    let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
    let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
endif

exe 'source' '~/.vim/plugins.vim'
exe 'source' '~/.vim/settings.vim'
exe 'source' '~/.vim/colors.vim'

for file in split(globpath('~/.vim', 'settings.*.vim'), '\n')
    exe 'source' file
endfor

exe 'source' '~/.vim/mappings.vim'
exe 'source' '~/.vim/commands.vim'

augroup general
    " Remove previous autocmds from this group (avoid execute it twice)
    autocmd!

    " Remove white space before save
    autocmd BufEnter * EnableStripWhitespaceOnSave
augroup end
